# FROM node:20

# WORKDIR /app 


# COPY ./app .

# #RUN npm install 
# # RUN npm run dev 
# # COPY ./autostart.sh /
# # RUN chmod +x /autostart.sh
# # ENTRYPOINT /autostart.sh
# # CMD ["npm","run","dev"]



